# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: false
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    packageType: runtime
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'my-vsts-feed'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: PublishPipelineArtifact@1
  inputs: 
   artifact: 'ducttse.Nextflip'